### ISSUE TITLE
Some reputations showing up incorrectly.

### ISSUE THREAD

**Issue by Arco-Dielhof** [AzerPUG/Multiple-Reputation-Tracker#10]
Reputations that have a different then standard minimum rep-name (EG. Court of Night) show up as a lower rep level (friendly while exalted).

Reputations with different rep level names (EG. Venari) show up as a different name then they are supposed to have. (Friendly while 'appreciated').

Check if there is a rep level index and if we are using that incorrectly.
Check if there is a rep level name, and see if we can put that on instead.

**Comment by royb3** [comment]
Fixed by @Arco-Dielhof  by addin Offset field to certain factions.
