### ISSUE TITLE
Mouse over max rep incorrect changes.

### ISSUE THREAD

**Issue by Arco-Dielhof** [AzerPUG/Multiple-Reputation-Tracker#11]
When mousing  over a maxed out reputation that can not gain paragon reputation, it shows XXXX/XXXX rep like the ones that can still gain more rep. However, they can not gain more rep and thus should not do anything on mouse over.

_Alternative: Instead of XXXX/XXXX rep, it could show "Maxed" or "Maxed Out" instead._

**Comment by royb3** [comment]
@Arco-Dielhof said he needs to look into this first.
