### ISSUE TITLE
Add DataTable Info if Paragon or Not

### ISSUE THREAD

**Issue by Arco-Dielhof** [AzerPUG/Multiple-Reputation-Tracker#13]
Right now a lot of reps are broken if they do not have Paragon Rep enabled. Make another section in the DataTable so the AddOn can figure out if it needs to deal with Paragon for the specific Rep.

Non-Paragon Rep:
Everything Pre-Legion
Archivists' Codex
Court of Night
The Avowed
Death's Advance
Honeyback Hive
Chromie
Akule Riverhorn
Conjurer Margoss
Talon's Vengeance

Ask Tex to help with DataTable Info.

**Comment by royb3** [comment]
C_Reputation.IsFactionParagon(factionID) is being used, also used in interface code to add the paragon bag.
